// Stock watchlist by parent sector ETF.
// Stocks are only fetched and scored when their parent sector is a rotation leader.
// Keep to 4-5 stocks per sector — each is a separate API call.
export const STOCK_WATCHLIST: Record<string, { symbol: string; label: string }[]> = {
    XLK: [
        { symbol: 'NVDA',  label: 'NVIDIA' },
        { symbol: 'MSFT',  label: 'Microsoft' },
        { symbol: 'AAPL',  label: 'Apple' },
        { symbol: 'AVGO',  label: 'Broadcom' },
        { symbol: 'AMD',   label: 'AMD' },
        { symbol: 'NBIS',  label: 'Nebius Group (AI Infra)' },
        { symbol: 'HPQ',   label: 'HP Inc' },
        { symbol: 'HPE',   label: 'Hewlett Packard Enterprise' },
        { symbol: 'PLTR',  label: 'Palantir (AI Data)' },
        { symbol: 'QBTS',  label: 'D-Wave Quantum' },
        { symbol: 'NOW',   label: 'ServiceNow' },
        { symbol: 'BB',    label: 'BlackBerry (Cybersecurity)' },
        { symbol: 'PANW',  label: 'Palo Alto Networks (Cybersecurity)' },
        { symbol: 'CSCO',  label: 'Cisco Systems' },
    ],
    XLF: [
        { symbol: 'JPM',   label: 'JPMorgan Chase' },
        { symbol: 'GS',    label: 'Goldman Sachs' },
        { symbol: 'MS',    label: 'Morgan Stanley' },
        { symbol: 'BAC',   label: 'Bank of America' },
        { symbol: 'V',     label: 'Visa' },
        { symbol: 'SOFI',  label: 'SoFi Technologies' },
        { symbol: 'PYPL',  label: 'PayPal' },
        { symbol: 'HOOD',  label: 'Robinhood Markets' },
        { symbol: 'NU',    label: 'Nubank (Latin America Fintech)' },
        { symbol: 'WFC',   label: 'Wells Fargo' },
        { symbol: 'HSBC',  label: 'HSBC Holdings' },
    ],
    XLV: [
        { symbol: 'LLY',   label: 'Eli Lilly' },
        { symbol: 'UNH',   label: 'UnitedHealth' },
        { symbol: 'ABBV',  label: 'AbbVie' },
        { symbol: 'JNJ',   label: 'Johnson & Johnson' },
        { symbol: 'MRK',   label: 'Merck' },
        { symbol: 'HIMS',  label: 'Hims & Hers (Telehealth)' },
    ],
    XLI: [
        { symbol: 'GE',    label: 'GE Aerospace' },
        { symbol: 'RTX',   label: 'RTX (Raytheon)' },
        { symbol: 'CAT',   label: 'Caterpillar' },
        { symbol: 'ETN',   label: 'Eaton' },
        { symbol: 'HON',   label: 'Honeywell' },
        { symbol: 'PWR',   label: 'Quanta Services (Electrical Infra)' },
        { symbol: 'BA',    label: 'Boeing' },
        { symbol: 'DAL',   label: 'Delta Air Lines' },
        { symbol: 'SPCX',  label: 'SpaceX (new IPO - building history)' },
    ],
    XLE: [
        { symbol: 'XOM',   label: 'ExxonMobil' },
        { symbol: 'CVX',   label: 'Chevron' },
        { symbol: 'COP',   label: 'ConocoPhillips' },
        { symbol: 'SLB',   label: 'SLB' },
        { symbol: 'EOG',   label: 'EOG Resources' },
        { symbol: 'FRVO',  label: 'Frontline (Oil Tankers)' },
        { symbol: 'BKR',   label: 'Baker Hughes (Oilfield Services)' },
        { symbol: 'USO',   label: 'United States Oil Fund (Crude Oil ETF)' },
    ],
    XLY: [
        { symbol: 'AMZN',  label: 'Amazon' },
        { symbol: 'TSLA',  label: 'Tesla' },
        { symbol: 'HD',    label: 'Home Depot' },
        { symbol: 'NKE',   label: 'Nike' },
        { symbol: 'TGT',   label: 'Target' },
        { symbol: 'F',     label: 'Ford Motor' },
        { symbol: 'RIVN',  label: 'Rivian Automotive' },
    ],
    XLB: [
        { symbol: 'FCX',   label: 'Freeport-McMoRan (Copper)' },
        { symbol: 'NUE',   label: 'Nucor (Steel)' },
        { symbol: 'LIN',   label: 'Linde (Industrial Gases)' },
        { symbol: 'SHW',   label: 'Sherwin-Williams' },
        { symbol: 'GLD',   label: 'SPDR Gold ETF' },
        { symbol: 'SLV',   label: 'iShares Silver ETF' },
    ],
    XLRE: [
        { symbol: 'PLD',   label: 'Prologis' },
        { symbol: 'EQIX',  label: 'Equinix' },
        { symbol: 'AMT',   label: 'American Tower' },
        { symbol: 'PSA',   label: 'Public Storage' },
        { symbol: 'O',     label: 'Realty Income' },
        { symbol: 'OPEN',  label: 'Opendoor (iBuying)' },
    ],
    XLU: [
        { symbol: 'NEE',   label: 'NextEra Energy' },
        { symbol: 'DUK',   label: 'Duke Energy' },
        { symbol: 'SO',    label: 'Southern Company' },
        { symbol: 'D',     label: 'Dominion Energy' },
        { symbol: 'BE',    label: 'Bloom Energy (Fuel Cell)' },
        { symbol: 'FCEL',  label: 'FuelCell Energy' },
        { symbol: 'ORA',   label: 'Ormat Technologies (Geothermal)' },
        { symbol: 'PCG',   label: 'PG&E (Pacific Gas & Electric)' },
    ],
    XLP: [
        { symbol: 'PG',    label: 'Procter & Gamble' },
        { symbol: 'KO',    label: 'Coca-Cola' },
        { symbol: 'PEP',   label: 'PepsiCo' },
        { symbol: 'WMT',   label: 'Walmart' },
        { symbol: 'COST',  label: 'Costco' },
    ],
    SMH: [
        { symbol: 'NVDA',  label: 'NVIDIA' },
        { symbol: 'TSM',   label: 'TSMC' },
        { symbol: 'AVGO',  label: 'Broadcom' },
        { symbol: 'AMD',   label: 'AMD' },
        { symbol: 'MU',    label: 'Micron' },
        { symbol: 'INTC',  label: 'Intel' },
    ],
    QQQ: [
        { symbol: 'MSFT',  label: 'Microsoft' },
        { symbol: 'AAPL',  label: 'Apple' },
        { symbol: 'NVDA',  label: 'NVIDIA' },
        { symbol: 'AMZN',  label: 'Amazon' },
        { symbol: 'GOOGL', label: 'Alphabet' },
    ],
    IWM: [
        { symbol: 'SMCI',  label: 'Super Micro Computer' },
        { symbol: 'CAVA',  label: 'CAVA Group' },
        { symbol: 'TOL',   label: 'Toll Brothers' },
        { symbol: 'RKT',   label: 'Rocket Companies' },
        { symbol: 'CHWY',  label: 'Chewy' },
        { symbol: 'KEEL',  label: 'Keelvar' },
        { symbol: 'IREN',  label: 'Iris Energy (AI Compute/BTC)' },
        { symbol: 'RIOT',  label: 'Riot Platforms (BTC Mining)' },
        { symbol: 'CIFR',  label: 'Cipher Mining (BTC Mining)' },
        { symbol: 'CLSK',  label: 'CleanSpark (BTC Mining)' },
        { symbol: 'IBIT',  label: 'iShares Bitcoin ETF' },
        { symbol: 'SKHY',  label: 'SKHY (new listing - building history)' },
    ],
};
