package com.rotationtracker.config

/** Stock watchlist keyed by parent sector ETF. Only fetched when the sector is a rotation leader. */
val STOCK_WATCHLIST: Map<String, List<Pair<String, String>>> = mapOf(
    "XLK" to listOf(
        "NVDA"  to "NVIDIA",
        "MSFT"  to "Microsoft",
        "AAPL"  to "Apple",
        "AVGO"  to "Broadcom",
        "AMD"   to "AMD",
        "NBIS"  to "Nebius Group (AI Infra)",
        "HPQ"   to "HP Inc",
        "HPE"   to "Hewlett Packard Enterprise",
        "PLTR"  to "Palantir (AI Data)",
        "QBTS"  to "D-Wave Quantum",
        "NOW"   to "ServiceNow",
        "BB"    to "BlackBerry (Cybersecurity)",
        "PANW"  to "Palo Alto Networks (Cybersecurity)",
        "CSCO"  to "Cisco Systems",
    ),
    "XLF" to listOf(
        "JPM"   to "JPMorgan Chase",
        "GS"    to "Goldman Sachs",
        "MS"    to "Morgan Stanley",
        "BAC"   to "Bank of America",
        "V"     to "Visa",
        "SOFI"  to "SoFi Technologies",
        "PYPL"  to "PayPal",
        "HOOD"  to "Robinhood Markets",
        "NU"    to "Nubank (Latin America Fintech)",
        "WFC"   to "Wells Fargo",
        "HSBC"  to "HSBC Holdings",
    ),
    "XLV" to listOf(
        "LLY"   to "Eli Lilly",
        "UNH"   to "UnitedHealth",
        "ABBV"  to "AbbVie",
        "JNJ"   to "Johnson & Johnson",
        "MRK"   to "Merck",
        "HIMS"  to "Hims & Hers (Telehealth)",
    ),
    "XLI" to listOf(
        "GE"    to "GE Aerospace",
        "RTX"   to "RTX (Raytheon)",
        "CAT"   to "Caterpillar",
        "ETN"   to "Eaton",
        "HON"   to "Honeywell",
        "PWR"   to "Quanta Services (Electrical Infra)",
        "BA"    to "Boeing",
        "DAL"   to "Delta Air Lines",
        "SPCX"  to "SpaceX (new IPO - building history)",
    ),
    "XLE" to listOf(
        "XOM"   to "ExxonMobil",
        "CVX"   to "Chevron",
        "COP"   to "ConocoPhillips",
        "SLB"   to "SLB",
        "EOG"   to "EOG Resources",
        "FRVO"  to "Frontline (Oil Tankers)",
        "BKR"   to "Baker Hughes (Oilfield Services)",
        "USO"   to "United States Oil Fund (Crude Oil ETF)",
    ),
    "XLY" to listOf(
        "AMZN"  to "Amazon",
        "TSLA"  to "Tesla",
        "HD"    to "Home Depot",
        "NKE"   to "Nike",
        "TGT"   to "Target",
        "F"     to "Ford Motor",
        "RIVN"  to "Rivian Automotive",
    ),
    "XLB" to listOf(
        "FCX"   to "Freeport-McMoRan (Copper)",
        "NUE"   to "Nucor (Steel)",
        "LIN"   to "Linde (Industrial Gases)",
        "SHW"   to "Sherwin-Williams",
        "GLD"   to "SPDR Gold ETF",
        "SLV"   to "iShares Silver ETF",
    ),
    "XLRE" to listOf(
        "PLD"   to "Prologis",
        "EQIX"  to "Equinix",
        "AMT"   to "American Tower",
        "PSA"   to "Public Storage",
        "O"     to "Realty Income",
        "OPEN"  to "Opendoor (iBuying)",
    ),
    "XLU" to listOf(
        "NEE"   to "NextEra Energy",
        "DUK"   to "Duke Energy",
        "SO"    to "Southern Company",
        "D"     to "Dominion Energy",
        "BE"    to "Bloom Energy (Fuel Cell)",
        "FCEL"  to "FuelCell Energy",
        "ORA"   to "Ormat Technologies (Geothermal)",
        "PCG"   to "PG&E (Pacific Gas & Electric)",
    ),
    "XLP" to listOf(
        "PG"    to "Procter & Gamble",
        "KO"    to "Coca-Cola",
        "PEP"   to "PepsiCo",
        "WMT"   to "Walmart",
        "COST"  to "Costco",
        "HELE"  to "Helen of Troy (Household & Personal Products)",
    ),
    "SMH" to listOf(
        "NVDA"  to "NVIDIA",
        "TSM"   to "TSMC",
        "AVGO"  to "Broadcom",
        "AMD"   to "AMD",
        "MU"    to "Micron",
        "INTC"  to "Intel",
    ),
    "QQQ" to listOf(
        "MSFT"  to "Microsoft",
        "AAPL"  to "Apple",
        "NVDA"  to "NVIDIA",
        "AMZN"  to "Amazon",
        "GOOGL" to "Alphabet",
    ),
    "IWM" to listOf(
        "SMCI"  to "Super Micro Computer",
        "CAVA"  to "CAVA Group",
        "TOL"   to "Toll Brothers",
        "RKT"   to "Rocket Companies",
        "CHWY"  to "Chewy",
        "KEEL"  to "Keelvar",
        "IREN"  to "Iris Energy (AI Compute/BTC)",
        "RIOT"  to "Riot Platforms (BTC Mining)",
        "CIFR"  to "Cipher Mining (BTC Mining)",
        "CLSK"  to "CleanSpark (BTC Mining)",
        "IBIT"  to "iShares Bitcoin ETF",
        "SKHY"  to "SKHY (new listing - building history)",
    ),
)
